;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        electric-align-SPC
        org-cycle
        org-end-of-line
        org-metaright
        org-self-insert-command
        org-shiftmetaright
        overwrite-mode
        slime-space
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '())
